#配置redis
#配置使用redis的具体哪个库
spring.redis.database=0
#配置远程访问地址
spring.redis.host=127.0.0.1
#端口号
spring.redis.port=6379
#最大连接数量
spring.redis.pool.max-active=8
spring.redis.pool.max-wait=-1
#空闲时连接数量
spring.redis.pool.max-idle=8
spring.redis.pool.min-idle=0
spring.redis.timeout=0